package chatAPP.model;

import java.util.Date;

public class ChatMsg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_msg.id
     *
     * @mbg.generated Wed Mar 20 22:15:43 AEDT 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_msg.sender
     *
     * @mbg.generated Wed Mar 20 22:15:43 AEDT 2019
     */
    private Integer sender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_msg.receiver
     *
     * @mbg.generated Wed Mar 20 22:15:43 AEDT 2019
     */
    private Integer receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_msg.msg
     *
     * @mbg.generated Wed Mar 20 22:15:43 AEDT 2019
     */
    private String msg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_msg.sign_flag
     *
     * @mbg.generated Wed Mar 20 22:15:43 AEDT 2019
     */
    private Integer signFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_msg.create_at
     *
     * @mbg.generated Wed Mar 20 22:15:43 AEDT 2019
     */
    private Date createAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_msg.id
     *
     * @return the value of chat_msg.id
     *
     * @mbg.generated Wed Mar 20 22:15:43 AEDT 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_msg.id
     *
     * @param id the value for chat_msg.id
     *
     * @mbg.generated Wed Mar 20 22:15:43 AEDT 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_msg.sender
     *
     * @return the value of chat_msg.sender
     *
     * @mbg.generated Wed Mar 20 22:15:43 AEDT 2019
     */
    public Integer getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_msg.sender
     *
     * @param sender the value for chat_msg.sender
     *
     * @mbg.generated Wed Mar 20 22:15:43 AEDT 2019
     */
    public void setSender(Integer sender) {
        this.sender = sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_msg.receiver
     *
     * @return the value of chat_msg.receiver
     *
     * @mbg.generated Wed Mar 20 22:15:43 AEDT 2019
     */
    public Integer getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_msg.receiver
     *
     * @param receiver the value for chat_msg.receiver
     *
     * @mbg.generated Wed Mar 20 22:15:43 AEDT 2019
     */
    public void setReceiver(Integer receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_msg.msg
     *
     * @return the value of chat_msg.msg
     *
     * @mbg.generated Wed Mar 20 22:15:43 AEDT 2019
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_msg.msg
     *
     * @param msg the value for chat_msg.msg
     *
     * @mbg.generated Wed Mar 20 22:15:43 AEDT 2019
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_msg.sign_flag
     *
     * @return the value of chat_msg.sign_flag
     *
     * @mbg.generated Wed Mar 20 22:15:43 AEDT 2019
     */
    public Integer getSignFlag() {
        return signFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_msg.sign_flag
     *
     * @param signFlag the value for chat_msg.sign_flag
     *
     * @mbg.generated Wed Mar 20 22:15:43 AEDT 2019
     */
    public void setSignFlag(Integer signFlag) {
        this.signFlag = signFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_msg.create_at
     *
     * @return the value of chat_msg.create_at
     *
     * @mbg.generated Wed Mar 20 22:15:43 AEDT 2019
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_msg.create_at
     *
     * @param createAt the value for chat_msg.create_at
     *
     * @mbg.generated Wed Mar 20 22:15:43 AEDT 2019
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }
}