package chatAPP.model;

public class Friends {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.id
     *
     * @mbg.generated Wed Mar 20 22:15:43 AEDT 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.user_id
     *
     * @mbg.generated Wed Mar 20 22:15:43 AEDT 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.friend_id
     *
     * @mbg.generated Wed Mar 20 22:15:43 AEDT 2019
     */
    private Integer friendId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.id
     *
     * @return the value of friends.id
     *
     * @mbg.generated Wed Mar 20 22:15:43 AEDT 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.id
     *
     * @param id the value for friends.id
     *
     * @mbg.generated Wed Mar 20 22:15:43 AEDT 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.user_id
     *
     * @return the value of friends.user_id
     *
     * @mbg.generated Wed Mar 20 22:15:43 AEDT 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.user_id
     *
     * @param userId the value for friends.user_id
     *
     * @mbg.generated Wed Mar 20 22:15:43 AEDT 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.friend_id
     *
     * @return the value of friends.friend_id
     *
     * @mbg.generated Wed Mar 20 22:15:43 AEDT 2019
     */
    public Integer getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.friend_id
     *
     * @param friendId the value for friends.friend_id
     *
     * @mbg.generated Wed Mar 20 22:15:43 AEDT 2019
     */
    public void setFriendId(Integer friendId) {
        this.friendId = friendId;
    }
}